// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: proto/perm_center.proto

package perm_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PermissionCenterService_BindDevice_FullMethodName                  = "/iot.permission.PermissionCenterService/BindDevice"
	PermissionCenterService_UnbindDevice_FullMethodName                = "/iot.permission.PermissionCenterService/UnbindDevice"
	PermissionCenterService_AuthorizeDevicePermission_FullMethodName   = "/iot.permission.PermissionCenterService/AuthorizeDevicePermission"
	PermissionCenterService_RevokeDevicePermission_FullMethodName      = "/iot.permission.PermissionCenterService/RevokeDevicePermission"
	PermissionCenterService_GetDevicePermission_FullMethodName         = "/iot.permission.PermissionCenterService/GetDevicePermission"
	PermissionCenterService_BatchDeleteDevicePermission_FullMethodName = "/iot.permission.PermissionCenterService/BatchDeleteDevicePermission"
	PermissionCenterService_GetDevicePermissionUsers_FullMethodName    = "/iot.permission.PermissionCenterService/GetDevicePermissionUsers"
	PermissionCenterService_BatchGetUserDevices_FullMethodName         = "/iot.permission.PermissionCenterService/BatchGetUserDevices"
	PermissionCenterService_BatchGetDevicePerms_FullMethodName         = "/iot.permission.PermissionCenterService/BatchGetDevicePerms"
	PermissionCenterService_AddApiPerm_FullMethodName                  = "/iot.permission.PermissionCenterService/AddApiPerm"
	PermissionCenterService_UpdateApiPerm_FullMethodName               = "/iot.permission.PermissionCenterService/UpdateApiPerm"
	PermissionCenterService_DeleteApiPerm_FullMethodName               = "/iot.permission.PermissionCenterService/DeleteApiPerm"
	PermissionCenterService_ListApiPerm_FullMethodName                 = "/iot.permission.PermissionCenterService/ListApiPerm"
	PermissionCenterService_AddRole_FullMethodName                     = "/iot.permission.PermissionCenterService/AddRole"
	PermissionCenterService_UpdateRole_FullMethodName                  = "/iot.permission.PermissionCenterService/UpdateRole"
	PermissionCenterService_DeleteRole_FullMethodName                  = "/iot.permission.PermissionCenterService/DeleteRole"
	PermissionCenterService_ListRole_FullMethodName                    = "/iot.permission.PermissionCenterService/ListRole"
	PermissionCenterService_BindRoleApi_FullMethodName                 = "/iot.permission.PermissionCenterService/BindRoleApi"
	PermissionCenterService_UnbindRoleApi_FullMethodName               = "/iot.permission.PermissionCenterService/UnbindRoleApi"
	PermissionCenterService_ListRoleApi_FullMethodName                 = "/iot.permission.PermissionCenterService/ListRoleApi"
	PermissionCenterService_ListOperLog_FullMethodName                 = "/iot.permission.PermissionCenterService/ListOperLog"
	PermissionCenterService_CheckDevicePerm_FullMethodName             = "/iot.permission.PermissionCenterService/CheckDevicePerm"
	PermissionCenterService_CheckApiPerm_FullMethodName                = "/iot.permission.PermissionCenterService/CheckApiPerm"
)

// PermissionCenterServiceClient is the client API for PermissionCenterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PermissionCenterServiceClient interface {
	// 【原有9个设备权限接口】100%保留
	BindDevice(ctx context.Context, in *BindDeviceRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	UnbindDevice(ctx context.Context, in *UnbindDeviceRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	AuthorizeDevicePermission(ctx context.Context, in *AuthorizeDevicePermissionRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	RevokeDevicePermission(ctx context.Context, in *RevokeDevicePermissionRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetDevicePermission(ctx context.Context, in *GetDevicePermissionRequest, opts ...grpc.CallOption) (*GetDevicePermissionResponse, error)
	BatchDeleteDevicePermission(ctx context.Context, in *BatchDeleteDevicePermissionRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetDevicePermissionUsers(ctx context.Context, in *GetDevicePermissionUsersRequest, opts ...grpc.CallOption) (*GetDevicePermissionUsersResponse, error)
	BatchGetUserDevices(ctx context.Context, in *BatchGetUserDevicesRequest, opts ...grpc.CallOption) (*BatchGetUserDevicesResponse, error)
	BatchGetDevicePerms(ctx context.Context, in *BatchGetDevicePermsRequest, opts ...grpc.CallOption) (*BatchGetDevicePermsResponse, error)
	// 【新增4个API权限管理接口】
	AddApiPerm(ctx context.Context, in *AddApiPermRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	UpdateApiPerm(ctx context.Context, in *UpdateApiPermRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	DeleteApiPerm(ctx context.Context, in *DeleteApiPermRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	ListApiPerm(ctx context.Context, in *ListApiPermRequest, opts ...grpc.CallOption) (*ListApiPermResponse, error)
	// 【新增7个角色管理接口】
	AddRole(ctx context.Context, in *AddRoleRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	ListRole(ctx context.Context, in *ListRoleRequest, opts ...grpc.CallOption) (*ListRoleResponse, error)
	BindRoleApi(ctx context.Context, in *BindRoleApiRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	UnbindRoleApi(ctx context.Context, in *UnbindRoleApiRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	ListRoleApi(ctx context.Context, in *ListRoleApiRequest, opts ...grpc.CallOption) (*ListRoleApiResponse, error)
	// 【新增1个操作日志查询接口】
	ListOperLog(ctx context.Context, in *ListOperLogRequest, opts ...grpc.CallOption) (*ListOperLogResponse, error)
	// 【新增2个核心权限校验接口】
	CheckDevicePerm(ctx context.Context, in *CheckDevicePermRequest, opts ...grpc.CallOption) (*CheckDevicePermResponse, error)
	CheckApiPerm(ctx context.Context, in *CheckApiPermRequest, opts ...grpc.CallOption) (*CheckApiPermResponse, error)
}

type permissionCenterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPermissionCenterServiceClient(cc grpc.ClientConnInterface) PermissionCenterServiceClient {
	return &permissionCenterServiceClient{cc}
}

func (c *permissionCenterServiceClient) BindDevice(ctx context.Context, in *BindDeviceRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_BindDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) UnbindDevice(ctx context.Context, in *UnbindDeviceRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_UnbindDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) AuthorizeDevicePermission(ctx context.Context, in *AuthorizeDevicePermissionRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_AuthorizeDevicePermission_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) RevokeDevicePermission(ctx context.Context, in *RevokeDevicePermissionRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_RevokeDevicePermission_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) GetDevicePermission(ctx context.Context, in *GetDevicePermissionRequest, opts ...grpc.CallOption) (*GetDevicePermissionResponse, error) {
	out := new(GetDevicePermissionResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_GetDevicePermission_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) BatchDeleteDevicePermission(ctx context.Context, in *BatchDeleteDevicePermissionRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_BatchDeleteDevicePermission_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) GetDevicePermissionUsers(ctx context.Context, in *GetDevicePermissionUsersRequest, opts ...grpc.CallOption) (*GetDevicePermissionUsersResponse, error) {
	out := new(GetDevicePermissionUsersResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_GetDevicePermissionUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) BatchGetUserDevices(ctx context.Context, in *BatchGetUserDevicesRequest, opts ...grpc.CallOption) (*BatchGetUserDevicesResponse, error) {
	out := new(BatchGetUserDevicesResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_BatchGetUserDevices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) BatchGetDevicePerms(ctx context.Context, in *BatchGetDevicePermsRequest, opts ...grpc.CallOption) (*BatchGetDevicePermsResponse, error) {
	out := new(BatchGetDevicePermsResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_BatchGetDevicePerms_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) AddApiPerm(ctx context.Context, in *AddApiPermRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_AddApiPerm_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) UpdateApiPerm(ctx context.Context, in *UpdateApiPermRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_UpdateApiPerm_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) DeleteApiPerm(ctx context.Context, in *DeleteApiPermRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_DeleteApiPerm_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) ListApiPerm(ctx context.Context, in *ListApiPermRequest, opts ...grpc.CallOption) (*ListApiPermResponse, error) {
	out := new(ListApiPermResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_ListApiPerm_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) AddRole(ctx context.Context, in *AddRoleRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_AddRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_UpdateRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_DeleteRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) ListRole(ctx context.Context, in *ListRoleRequest, opts ...grpc.CallOption) (*ListRoleResponse, error) {
	out := new(ListRoleResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_ListRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) BindRoleApi(ctx context.Context, in *BindRoleApiRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_BindRoleApi_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) UnbindRoleApi(ctx context.Context, in *UnbindRoleApiRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_UnbindRoleApi_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) ListRoleApi(ctx context.Context, in *ListRoleApiRequest, opts ...grpc.CallOption) (*ListRoleApiResponse, error) {
	out := new(ListRoleApiResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_ListRoleApi_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) ListOperLog(ctx context.Context, in *ListOperLogRequest, opts ...grpc.CallOption) (*ListOperLogResponse, error) {
	out := new(ListOperLogResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_ListOperLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) CheckDevicePerm(ctx context.Context, in *CheckDevicePermRequest, opts ...grpc.CallOption) (*CheckDevicePermResponse, error) {
	out := new(CheckDevicePermResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_CheckDevicePerm_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionCenterServiceClient) CheckApiPerm(ctx context.Context, in *CheckApiPermRequest, opts ...grpc.CallOption) (*CheckApiPermResponse, error) {
	out := new(CheckApiPermResponse)
	err := c.cc.Invoke(ctx, PermissionCenterService_CheckApiPerm_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermissionCenterServiceServer is the server API for PermissionCenterService service.
// All implementations must embed UnimplementedPermissionCenterServiceServer
// for forward compatibility
type PermissionCenterServiceServer interface {
	// 【原有9个设备权限接口】100%保留
	BindDevice(context.Context, *BindDeviceRequest) (*BaseResponse, error)
	UnbindDevice(context.Context, *UnbindDeviceRequest) (*BaseResponse, error)
	AuthorizeDevicePermission(context.Context, *AuthorizeDevicePermissionRequest) (*BaseResponse, error)
	RevokeDevicePermission(context.Context, *RevokeDevicePermissionRequest) (*BaseResponse, error)
	GetDevicePermission(context.Context, *GetDevicePermissionRequest) (*GetDevicePermissionResponse, error)
	BatchDeleteDevicePermission(context.Context, *BatchDeleteDevicePermissionRequest) (*BaseResponse, error)
	GetDevicePermissionUsers(context.Context, *GetDevicePermissionUsersRequest) (*GetDevicePermissionUsersResponse, error)
	BatchGetUserDevices(context.Context, *BatchGetUserDevicesRequest) (*BatchGetUserDevicesResponse, error)
	BatchGetDevicePerms(context.Context, *BatchGetDevicePermsRequest) (*BatchGetDevicePermsResponse, error)
	// 【新增4个API权限管理接口】
	AddApiPerm(context.Context, *AddApiPermRequest) (*BaseResponse, error)
	UpdateApiPerm(context.Context, *UpdateApiPermRequest) (*BaseResponse, error)
	DeleteApiPerm(context.Context, *DeleteApiPermRequest) (*BaseResponse, error)
	ListApiPerm(context.Context, *ListApiPermRequest) (*ListApiPermResponse, error)
	// 【新增7个角色管理接口】
	AddRole(context.Context, *AddRoleRequest) (*BaseResponse, error)
	UpdateRole(context.Context, *UpdateRoleRequest) (*BaseResponse, error)
	DeleteRole(context.Context, *DeleteRoleRequest) (*BaseResponse, error)
	ListRole(context.Context, *ListRoleRequest) (*ListRoleResponse, error)
	BindRoleApi(context.Context, *BindRoleApiRequest) (*BaseResponse, error)
	UnbindRoleApi(context.Context, *UnbindRoleApiRequest) (*BaseResponse, error)
	ListRoleApi(context.Context, *ListRoleApiRequest) (*ListRoleApiResponse, error)
	// 【新增1个操作日志查询接口】
	ListOperLog(context.Context, *ListOperLogRequest) (*ListOperLogResponse, error)
	// 【新增2个核心权限校验接口】
	CheckDevicePerm(context.Context, *CheckDevicePermRequest) (*CheckDevicePermResponse, error)
	CheckApiPerm(context.Context, *CheckApiPermRequest) (*CheckApiPermResponse, error)
	mustEmbedUnimplementedPermissionCenterServiceServer()
}

// UnimplementedPermissionCenterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPermissionCenterServiceServer struct {
}

func (UnimplementedPermissionCenterServiceServer) BindDevice(context.Context, *BindDeviceRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindDevice not implemented")
}
func (UnimplementedPermissionCenterServiceServer) UnbindDevice(context.Context, *UnbindDeviceRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnbindDevice not implemented")
}
func (UnimplementedPermissionCenterServiceServer) AuthorizeDevicePermission(context.Context, *AuthorizeDevicePermissionRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeDevicePermission not implemented")
}
func (UnimplementedPermissionCenterServiceServer) RevokeDevicePermission(context.Context, *RevokeDevicePermissionRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeDevicePermission not implemented")
}
func (UnimplementedPermissionCenterServiceServer) GetDevicePermission(context.Context, *GetDevicePermissionRequest) (*GetDevicePermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevicePermission not implemented")
}
func (UnimplementedPermissionCenterServiceServer) BatchDeleteDevicePermission(context.Context, *BatchDeleteDevicePermissionRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteDevicePermission not implemented")
}
func (UnimplementedPermissionCenterServiceServer) GetDevicePermissionUsers(context.Context, *GetDevicePermissionUsersRequest) (*GetDevicePermissionUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevicePermissionUsers not implemented")
}
func (UnimplementedPermissionCenterServiceServer) BatchGetUserDevices(context.Context, *BatchGetUserDevicesRequest) (*BatchGetUserDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetUserDevices not implemented")
}
func (UnimplementedPermissionCenterServiceServer) BatchGetDevicePerms(context.Context, *BatchGetDevicePermsRequest) (*BatchGetDevicePermsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetDevicePerms not implemented")
}
func (UnimplementedPermissionCenterServiceServer) AddApiPerm(context.Context, *AddApiPermRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddApiPerm not implemented")
}
func (UnimplementedPermissionCenterServiceServer) UpdateApiPerm(context.Context, *UpdateApiPermRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApiPerm not implemented")
}
func (UnimplementedPermissionCenterServiceServer) DeleteApiPerm(context.Context, *DeleteApiPermRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteApiPerm not implemented")
}
func (UnimplementedPermissionCenterServiceServer) ListApiPerm(context.Context, *ListApiPermRequest) (*ListApiPermResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApiPerm not implemented")
}
func (UnimplementedPermissionCenterServiceServer) AddRole(context.Context, *AddRoleRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRole not implemented")
}
func (UnimplementedPermissionCenterServiceServer) UpdateRole(context.Context, *UpdateRoleRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRole not implemented")
}
func (UnimplementedPermissionCenterServiceServer) DeleteRole(context.Context, *DeleteRoleRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRole not implemented")
}
func (UnimplementedPermissionCenterServiceServer) ListRole(context.Context, *ListRoleRequest) (*ListRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRole not implemented")
}
func (UnimplementedPermissionCenterServiceServer) BindRoleApi(context.Context, *BindRoleApiRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindRoleApi not implemented")
}
func (UnimplementedPermissionCenterServiceServer) UnbindRoleApi(context.Context, *UnbindRoleApiRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnbindRoleApi not implemented")
}
func (UnimplementedPermissionCenterServiceServer) ListRoleApi(context.Context, *ListRoleApiRequest) (*ListRoleApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoleApi not implemented")
}
func (UnimplementedPermissionCenterServiceServer) ListOperLog(context.Context, *ListOperLogRequest) (*ListOperLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOperLog not implemented")
}
func (UnimplementedPermissionCenterServiceServer) CheckDevicePerm(context.Context, *CheckDevicePermRequest) (*CheckDevicePermResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckDevicePerm not implemented")
}
func (UnimplementedPermissionCenterServiceServer) CheckApiPerm(context.Context, *CheckApiPermRequest) (*CheckApiPermResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckApiPerm not implemented")
}
func (UnimplementedPermissionCenterServiceServer) mustEmbedUnimplementedPermissionCenterServiceServer() {
}

// UnsafePermissionCenterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermissionCenterServiceServer will
// result in compilation errors.
type UnsafePermissionCenterServiceServer interface {
	mustEmbedUnimplementedPermissionCenterServiceServer()
}

func RegisterPermissionCenterServiceServer(s grpc.ServiceRegistrar, srv PermissionCenterServiceServer) {
	s.RegisterService(&PermissionCenterService_ServiceDesc, srv)
}

func _PermissionCenterService_BindDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).BindDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_BindDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).BindDevice(ctx, req.(*BindDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_UnbindDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).UnbindDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_UnbindDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).UnbindDevice(ctx, req.(*UnbindDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_AuthorizeDevicePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeDevicePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).AuthorizeDevicePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_AuthorizeDevicePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).AuthorizeDevicePermission(ctx, req.(*AuthorizeDevicePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_RevokeDevicePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeDevicePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).RevokeDevicePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_RevokeDevicePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).RevokeDevicePermission(ctx, req.(*RevokeDevicePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_GetDevicePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevicePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).GetDevicePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_GetDevicePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).GetDevicePermission(ctx, req.(*GetDevicePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_BatchDeleteDevicePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteDevicePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).BatchDeleteDevicePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_BatchDeleteDevicePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).BatchDeleteDevicePermission(ctx, req.(*BatchDeleteDevicePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_GetDevicePermissionUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevicePermissionUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).GetDevicePermissionUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_GetDevicePermissionUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).GetDevicePermissionUsers(ctx, req.(*GetDevicePermissionUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_BatchGetUserDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetUserDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).BatchGetUserDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_BatchGetUserDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).BatchGetUserDevices(ctx, req.(*BatchGetUserDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_BatchGetDevicePerms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetDevicePermsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).BatchGetDevicePerms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_BatchGetDevicePerms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).BatchGetDevicePerms(ctx, req.(*BatchGetDevicePermsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_AddApiPerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddApiPermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).AddApiPerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_AddApiPerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).AddApiPerm(ctx, req.(*AddApiPermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_UpdateApiPerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApiPermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).UpdateApiPerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_UpdateApiPerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).UpdateApiPerm(ctx, req.(*UpdateApiPermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_DeleteApiPerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApiPermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).DeleteApiPerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_DeleteApiPerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).DeleteApiPerm(ctx, req.(*DeleteApiPermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_ListApiPerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApiPermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).ListApiPerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_ListApiPerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).ListApiPerm(ctx, req.(*ListApiPermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_AddRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).AddRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_AddRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).AddRole(ctx, req.(*AddRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_UpdateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).UpdateRole(ctx, req.(*UpdateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_DeleteRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).DeleteRole(ctx, req.(*DeleteRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_ListRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).ListRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_ListRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).ListRole(ctx, req.(*ListRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_BindRoleApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindRoleApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).BindRoleApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_BindRoleApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).BindRoleApi(ctx, req.(*BindRoleApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_UnbindRoleApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindRoleApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).UnbindRoleApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_UnbindRoleApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).UnbindRoleApi(ctx, req.(*UnbindRoleApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_ListRoleApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoleApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).ListRoleApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_ListRoleApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).ListRoleApi(ctx, req.(*ListRoleApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_ListOperLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).ListOperLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_ListOperLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).ListOperLog(ctx, req.(*ListOperLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_CheckDevicePerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDevicePermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).CheckDevicePerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_CheckDevicePerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).CheckDevicePerm(ctx, req.(*CheckDevicePermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionCenterService_CheckApiPerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckApiPermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionCenterServiceServer).CheckApiPerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionCenterService_CheckApiPerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionCenterServiceServer).CheckApiPerm(ctx, req.(*CheckApiPermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PermissionCenterService_ServiceDesc is the grpc.ServiceDesc for PermissionCenterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PermissionCenterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iot.permission.PermissionCenterService",
	HandlerType: (*PermissionCenterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BindDevice",
			Handler:    _PermissionCenterService_BindDevice_Handler,
		},
		{
			MethodName: "UnbindDevice",
			Handler:    _PermissionCenterService_UnbindDevice_Handler,
		},
		{
			MethodName: "AuthorizeDevicePermission",
			Handler:    _PermissionCenterService_AuthorizeDevicePermission_Handler,
		},
		{
			MethodName: "RevokeDevicePermission",
			Handler:    _PermissionCenterService_RevokeDevicePermission_Handler,
		},
		{
			MethodName: "GetDevicePermission",
			Handler:    _PermissionCenterService_GetDevicePermission_Handler,
		},
		{
			MethodName: "BatchDeleteDevicePermission",
			Handler:    _PermissionCenterService_BatchDeleteDevicePermission_Handler,
		},
		{
			MethodName: "GetDevicePermissionUsers",
			Handler:    _PermissionCenterService_GetDevicePermissionUsers_Handler,
		},
		{
			MethodName: "BatchGetUserDevices",
			Handler:    _PermissionCenterService_BatchGetUserDevices_Handler,
		},
		{
			MethodName: "BatchGetDevicePerms",
			Handler:    _PermissionCenterService_BatchGetDevicePerms_Handler,
		},
		{
			MethodName: "AddApiPerm",
			Handler:    _PermissionCenterService_AddApiPerm_Handler,
		},
		{
			MethodName: "UpdateApiPerm",
			Handler:    _PermissionCenterService_UpdateApiPerm_Handler,
		},
		{
			MethodName: "DeleteApiPerm",
			Handler:    _PermissionCenterService_DeleteApiPerm_Handler,
		},
		{
			MethodName: "ListApiPerm",
			Handler:    _PermissionCenterService_ListApiPerm_Handler,
		},
		{
			MethodName: "AddRole",
			Handler:    _PermissionCenterService_AddRole_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _PermissionCenterService_UpdateRole_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _PermissionCenterService_DeleteRole_Handler,
		},
		{
			MethodName: "ListRole",
			Handler:    _PermissionCenterService_ListRole_Handler,
		},
		{
			MethodName: "BindRoleApi",
			Handler:    _PermissionCenterService_BindRoleApi_Handler,
		},
		{
			MethodName: "UnbindRoleApi",
			Handler:    _PermissionCenterService_UnbindRoleApi_Handler,
		},
		{
			MethodName: "ListRoleApi",
			Handler:    _PermissionCenterService_ListRoleApi_Handler,
		},
		{
			MethodName: "ListOperLog",
			Handler:    _PermissionCenterService_ListOperLog_Handler,
		},
		{
			MethodName: "CheckDevicePerm",
			Handler:    _PermissionCenterService_CheckDevicePerm_Handler,
		},
		{
			MethodName: "CheckApiPerm",
			Handler:    _PermissionCenterService_CheckApiPerm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/perm_center.proto",
}
