// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: proto/perm.proto

package iot_permission

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IoTDevicePermissionService_BindDevice_FullMethodName                  = "/iot.permission.IoTDevicePermissionService/BindDevice"
	IoTDevicePermissionService_UnbindDevice_FullMethodName                = "/iot.permission.IoTDevicePermissionService/UnbindDevice"
	IoTDevicePermissionService_AuthorizeDevicePermission_FullMethodName   = "/iot.permission.IoTDevicePermissionService/AuthorizeDevicePermission"
	IoTDevicePermissionService_RevokeDevicePermission_FullMethodName      = "/iot.permission.IoTDevicePermissionService/RevokeDevicePermission"
	IoTDevicePermissionService_GetDevicePermission_FullMethodName         = "/iot.permission.IoTDevicePermissionService/GetDevicePermission"
	IoTDevicePermissionService_BatchDeleteDevicePermission_FullMethodName = "/iot.permission.IoTDevicePermissionService/BatchDeleteDevicePermission"
	IoTDevicePermissionService_GetDevicePermissionUsers_FullMethodName    = "/iot.permission.IoTDevicePermissionService/GetDevicePermissionUsers"
	IoTDevicePermissionService_BatchGetUserDevices_FullMethodName         = "/iot.permission.IoTDevicePermissionService/BatchGetUserDevices"
	IoTDevicePermissionService_BatchGetDevicePerms_FullMethodName         = "/iot.permission.IoTDevicePermissionService/BatchGetDevicePerms"
)

// IoTDevicePermissionServiceClient is the client API for IoTDevicePermissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IoTDevicePermissionServiceClient interface {
	// 绑定设备（成为OWNER）
	BindDevice(ctx context.Context, in *BindDeviceRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	// 解绑设备（删除OWNER权限）
	UnbindDevice(ctx context.Context, in *UnbindDeviceRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	// 授权其他用户设备权限
	AuthorizeDevicePermission(ctx context.Context, in *AuthorizeDevicePermissionRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	// 撤销其他用户设备权限
	RevokeDevicePermission(ctx context.Context, in *RevokeDevicePermissionRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	// 查询用户设备权限
	GetDevicePermission(ctx context.Context, in *GetDevicePermissionRequest, opts ...grpc.CallOption) (*GetDevicePermissionResponse, error)
	// 批量删除设备所有权限（设备注销）
	BatchDeleteDevicePermission(ctx context.Context, in *BatchDeleteDevicePermissionRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	// 查询设备的所有权限用户列表
	GetDevicePermissionUsers(ctx context.Context, in *GetDevicePermissionUsersRequest, opts ...grpc.CallOption) (*GetDevicePermissionUsersResponse, error)
	BatchGetUserDevices(ctx context.Context, in *BatchGetUserDevicesRequest, opts ...grpc.CallOption) (*BatchGetUserDevicesResponse, error)
	BatchGetDevicePerms(ctx context.Context, in *BatchGetDevicePermsRequest, opts ...grpc.CallOption) (*BatchGetDevicePermsResponse, error)
}

type ioTDevicePermissionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIoTDevicePermissionServiceClient(cc grpc.ClientConnInterface) IoTDevicePermissionServiceClient {
	return &ioTDevicePermissionServiceClient{cc}
}

func (c *ioTDevicePermissionServiceClient) BindDevice(ctx context.Context, in *BindDeviceRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, IoTDevicePermissionService_BindDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTDevicePermissionServiceClient) UnbindDevice(ctx context.Context, in *UnbindDeviceRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, IoTDevicePermissionService_UnbindDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTDevicePermissionServiceClient) AuthorizeDevicePermission(ctx context.Context, in *AuthorizeDevicePermissionRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, IoTDevicePermissionService_AuthorizeDevicePermission_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTDevicePermissionServiceClient) RevokeDevicePermission(ctx context.Context, in *RevokeDevicePermissionRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, IoTDevicePermissionService_RevokeDevicePermission_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTDevicePermissionServiceClient) GetDevicePermission(ctx context.Context, in *GetDevicePermissionRequest, opts ...grpc.CallOption) (*GetDevicePermissionResponse, error) {
	out := new(GetDevicePermissionResponse)
	err := c.cc.Invoke(ctx, IoTDevicePermissionService_GetDevicePermission_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTDevicePermissionServiceClient) BatchDeleteDevicePermission(ctx context.Context, in *BatchDeleteDevicePermissionRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, IoTDevicePermissionService_BatchDeleteDevicePermission_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTDevicePermissionServiceClient) GetDevicePermissionUsers(ctx context.Context, in *GetDevicePermissionUsersRequest, opts ...grpc.CallOption) (*GetDevicePermissionUsersResponse, error) {
	out := new(GetDevicePermissionUsersResponse)
	err := c.cc.Invoke(ctx, IoTDevicePermissionService_GetDevicePermissionUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTDevicePermissionServiceClient) BatchGetUserDevices(ctx context.Context, in *BatchGetUserDevicesRequest, opts ...grpc.CallOption) (*BatchGetUserDevicesResponse, error) {
	out := new(BatchGetUserDevicesResponse)
	err := c.cc.Invoke(ctx, IoTDevicePermissionService_BatchGetUserDevices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioTDevicePermissionServiceClient) BatchGetDevicePerms(ctx context.Context, in *BatchGetDevicePermsRequest, opts ...grpc.CallOption) (*BatchGetDevicePermsResponse, error) {
	out := new(BatchGetDevicePermsResponse)
	err := c.cc.Invoke(ctx, IoTDevicePermissionService_BatchGetDevicePerms_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IoTDevicePermissionServiceServer is the server API for IoTDevicePermissionService service.
// All implementations must embed UnimplementedIoTDevicePermissionServiceServer
// for forward compatibility
type IoTDevicePermissionServiceServer interface {
	// 绑定设备（成为OWNER）
	BindDevice(context.Context, *BindDeviceRequest) (*BaseResponse, error)
	// 解绑设备（删除OWNER权限）
	UnbindDevice(context.Context, *UnbindDeviceRequest) (*BaseResponse, error)
	// 授权其他用户设备权限
	AuthorizeDevicePermission(context.Context, *AuthorizeDevicePermissionRequest) (*BaseResponse, error)
	// 撤销其他用户设备权限
	RevokeDevicePermission(context.Context, *RevokeDevicePermissionRequest) (*BaseResponse, error)
	// 查询用户设备权限
	GetDevicePermission(context.Context, *GetDevicePermissionRequest) (*GetDevicePermissionResponse, error)
	// 批量删除设备所有权限（设备注销）
	BatchDeleteDevicePermission(context.Context, *BatchDeleteDevicePermissionRequest) (*BaseResponse, error)
	// 查询设备的所有权限用户列表
	GetDevicePermissionUsers(context.Context, *GetDevicePermissionUsersRequest) (*GetDevicePermissionUsersResponse, error)
	BatchGetUserDevices(context.Context, *BatchGetUserDevicesRequest) (*BatchGetUserDevicesResponse, error)
	BatchGetDevicePerms(context.Context, *BatchGetDevicePermsRequest) (*BatchGetDevicePermsResponse, error)
	mustEmbedUnimplementedIoTDevicePermissionServiceServer()
}

// UnimplementedIoTDevicePermissionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIoTDevicePermissionServiceServer struct {
}

func (UnimplementedIoTDevicePermissionServiceServer) BindDevice(context.Context, *BindDeviceRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindDevice not implemented")
}
func (UnimplementedIoTDevicePermissionServiceServer) UnbindDevice(context.Context, *UnbindDeviceRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnbindDevice not implemented")
}
func (UnimplementedIoTDevicePermissionServiceServer) AuthorizeDevicePermission(context.Context, *AuthorizeDevicePermissionRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeDevicePermission not implemented")
}
func (UnimplementedIoTDevicePermissionServiceServer) RevokeDevicePermission(context.Context, *RevokeDevicePermissionRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeDevicePermission not implemented")
}
func (UnimplementedIoTDevicePermissionServiceServer) GetDevicePermission(context.Context, *GetDevicePermissionRequest) (*GetDevicePermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevicePermission not implemented")
}
func (UnimplementedIoTDevicePermissionServiceServer) BatchDeleteDevicePermission(context.Context, *BatchDeleteDevicePermissionRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteDevicePermission not implemented")
}
func (UnimplementedIoTDevicePermissionServiceServer) GetDevicePermissionUsers(context.Context, *GetDevicePermissionUsersRequest) (*GetDevicePermissionUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevicePermissionUsers not implemented")
}
func (UnimplementedIoTDevicePermissionServiceServer) BatchGetUserDevices(context.Context, *BatchGetUserDevicesRequest) (*BatchGetUserDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetUserDevices not implemented")
}
func (UnimplementedIoTDevicePermissionServiceServer) BatchGetDevicePerms(context.Context, *BatchGetDevicePermsRequest) (*BatchGetDevicePermsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetDevicePerms not implemented")
}
func (UnimplementedIoTDevicePermissionServiceServer) mustEmbedUnimplementedIoTDevicePermissionServiceServer() {
}

// UnsafeIoTDevicePermissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IoTDevicePermissionServiceServer will
// result in compilation errors.
type UnsafeIoTDevicePermissionServiceServer interface {
	mustEmbedUnimplementedIoTDevicePermissionServiceServer()
}

func RegisterIoTDevicePermissionServiceServer(s grpc.ServiceRegistrar, srv IoTDevicePermissionServiceServer) {
	s.RegisterService(&IoTDevicePermissionService_ServiceDesc, srv)
}

func _IoTDevicePermissionService_BindDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTDevicePermissionServiceServer).BindDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoTDevicePermissionService_BindDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTDevicePermissionServiceServer).BindDevice(ctx, req.(*BindDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoTDevicePermissionService_UnbindDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTDevicePermissionServiceServer).UnbindDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoTDevicePermissionService_UnbindDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTDevicePermissionServiceServer).UnbindDevice(ctx, req.(*UnbindDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoTDevicePermissionService_AuthorizeDevicePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeDevicePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTDevicePermissionServiceServer).AuthorizeDevicePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoTDevicePermissionService_AuthorizeDevicePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTDevicePermissionServiceServer).AuthorizeDevicePermission(ctx, req.(*AuthorizeDevicePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoTDevicePermissionService_RevokeDevicePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeDevicePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTDevicePermissionServiceServer).RevokeDevicePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoTDevicePermissionService_RevokeDevicePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTDevicePermissionServiceServer).RevokeDevicePermission(ctx, req.(*RevokeDevicePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoTDevicePermissionService_GetDevicePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevicePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTDevicePermissionServiceServer).GetDevicePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoTDevicePermissionService_GetDevicePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTDevicePermissionServiceServer).GetDevicePermission(ctx, req.(*GetDevicePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoTDevicePermissionService_BatchDeleteDevicePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteDevicePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTDevicePermissionServiceServer).BatchDeleteDevicePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoTDevicePermissionService_BatchDeleteDevicePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTDevicePermissionServiceServer).BatchDeleteDevicePermission(ctx, req.(*BatchDeleteDevicePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoTDevicePermissionService_GetDevicePermissionUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevicePermissionUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTDevicePermissionServiceServer).GetDevicePermissionUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoTDevicePermissionService_GetDevicePermissionUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTDevicePermissionServiceServer).GetDevicePermissionUsers(ctx, req.(*GetDevicePermissionUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoTDevicePermissionService_BatchGetUserDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetUserDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTDevicePermissionServiceServer).BatchGetUserDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoTDevicePermissionService_BatchGetUserDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTDevicePermissionServiceServer).BatchGetUserDevices(ctx, req.(*BatchGetUserDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoTDevicePermissionService_BatchGetDevicePerms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetDevicePermsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoTDevicePermissionServiceServer).BatchGetDevicePerms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoTDevicePermissionService_BatchGetDevicePerms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoTDevicePermissionServiceServer).BatchGetDevicePerms(ctx, req.(*BatchGetDevicePermsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IoTDevicePermissionService_ServiceDesc is the grpc.ServiceDesc for IoTDevicePermissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IoTDevicePermissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iot.permission.IoTDevicePermissionService",
	HandlerType: (*IoTDevicePermissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BindDevice",
			Handler:    _IoTDevicePermissionService_BindDevice_Handler,
		},
		{
			MethodName: "UnbindDevice",
			Handler:    _IoTDevicePermissionService_UnbindDevice_Handler,
		},
		{
			MethodName: "AuthorizeDevicePermission",
			Handler:    _IoTDevicePermissionService_AuthorizeDevicePermission_Handler,
		},
		{
			MethodName: "RevokeDevicePermission",
			Handler:    _IoTDevicePermissionService_RevokeDevicePermission_Handler,
		},
		{
			MethodName: "GetDevicePermission",
			Handler:    _IoTDevicePermissionService_GetDevicePermission_Handler,
		},
		{
			MethodName: "BatchDeleteDevicePermission",
			Handler:    _IoTDevicePermissionService_BatchDeleteDevicePermission_Handler,
		},
		{
			MethodName: "GetDevicePermissionUsers",
			Handler:    _IoTDevicePermissionService_GetDevicePermissionUsers_Handler,
		},
		{
			MethodName: "BatchGetUserDevices",
			Handler:    _IoTDevicePermissionService_BatchGetUserDevices_Handler,
		},
		{
			MethodName: "BatchGetDevicePerms",
			Handler:    _IoTDevicePermissionService_BatchGetDevicePerms_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/perm.proto",
}
